return {
	"nvimdev/dashboard-nvim",
	event = "VimEnter",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	opts = {
		theme = "doom",
		config = {
			header = {
				"",
				"",
				"",
				"",
				"           ███████╗██████╗  █████╗  ██████╗███████╗           ",
				"           ██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝           ",
				"           ███████╗██████╔╝███████║██║     █████╗             ",
				"           ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝             ",
				"           ███████║██║     ██║  ██║╚██████╗███████╗           ",
				"           ╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝           ",
				"    ██████╗ ██████╗ ██╗    ██╗██████╗  ██████╗ ██╗   ██╗      ",
				"   ██╔════╝██╔═══██╗██║    ██║██╔══██╗██╔═══██╗╚██╗ ██╔╝      ",
				"   ██║     ██║   ██║██║ █╗ ██║██████╔╝██║   ██║ ╚████╔╝       ",
				"   ██║     ██║   ██║██║███╗██║██╔══██╗██║   ██║  ╚██╔╝        ",
				"   ╚██████╗╚██████╔╝╚███╔███╔╝██████╔╝╚██████╔╝   ██║██╗██╗██╗",
				"    ╚═════╝ ╚═════╝  ╚══╝╚══╝ ╚═════╝  ╚═════╝    ╚═╝╚═╝╚═╝╚═╝",
				"",
				"",
			},
			center = {
				{
					icon = " ",
					icon_hl = "Title",
					desc = "Browse Files    ",
					desc_hl = "String",
					key = "e",
					key_hl = "String",
					key_format = "  [%s]",
					action = "NvimTreeToggle",
				},
				{
					icon = " ",
					icon_hl = "Title",
					desc = "Recent Files    ",
					desc_hl = "String",
					key = "r",
					key_hl = "String",
					key_format = "  [%s]",
					action = "Telescope oldfiles",
				},
				{
					icon = " ",
					icon_hl = "Title",
					desc = "Find File    ",
					desc_hl = "String",
					key = "f",
					key_hl = "String",
					key_format = "  [%s]",
					action = "Telescope find_files",
				},
				{
					icon = " ",
					icon_hl = "Title",
					desc = "Find Word    ",
					desc_hl = "String",
					key = "g",
					key_hl = "String",
					key_format = "  [%s]",
					action = "Telescope live_grep",
				},
				{
					icon = " ",
					icon_hl = "Title",
					desc = "New Daily    ",
					desc_hl = "String",
					key = "d",
					key_hl = "String",
					key_format = "  [%s]",
					action = "ObsidianDailies",
				},
				{
					icon = " ",
					icon_hl = "Title",
					desc = "New Note    ",
					desc_hl = "String",
					key = "n",
					key_hl = "String",
					key_format = "  [%s]",
					action = "ObsidianNew",
				},
				{
					icon = " ",
					icon_hl = "Title",
					desc = "Search Notes    ",
					desc_hl = "String",
					key = "t",
					key_hl = "String",
					key_format = "  [%s]",
					action = "ObsidianSearch",
				},
				{
					icon = " ",
					icon_hl = "Title",
					desc = "Config    ",
					desc_hl = "String",
					key = "c",
					key_hl = "String",
					key_format = "  [%s]",
					action = "NvimTreeToggle ~/.config/nvim/lua/casey/config/",
				},
				{
					icon = " ",
					icon_hl = "Title",
					desc = "Plugins    ",
					desc_hl = "String",
					key = "p",
					key_hl = "String",
					key_format = "  [%s]",
					action = "NvimTreeOpen ~/.config/nvim/lua/casey/plugins/",
				},
				{
					icon = "󰩈 ",
					icon_hl = "Title",
					desc = "Quit    ",
					desc_hl = "String",
					key = "q",
					key_hl = "String",
					key_format = "  [%s]",
					action = "quit",
				},
			},
			vertical_center = false,
		},
	},
}
